#!/bin/bash
#SBATCH --job-name=d4_sobol2
#SBATCH --output=/home/fs02/pmr82_0001/ms3654/dissertation/D4_distributed_risk/logs/d4_sobol2_%A_%a.out
#SBATCH --error=/home/fs02/pmr82_0001/ms3654/dissertation/D4_distributed_risk/logs/d4_sobol2_%A_%a.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=50
#SBATCH --mem=64G
#SBATCH --time=02:00:00
#SBATCH --partition=normal
#
# D4 Sobol Sweep 2 — k=7 parameters (adds erq_cap_mg from 1954 Decree Art. III-B-1(d)).
# Total: 16,384 tasks × 50 Kirsch-Nowak realizations, run in parallel (50 workers/task).
#
# New vs sweep 1:
#   - erq_cap_mg added (50,000–100,000 MG; Decree 70 BG baseline)
#   - pywrdrb now includes ERQRelease (implemented 2026-06-02)
#   - erq_annual_release_mg, erq_seasonal_exhaustion_rate, erq_days_released added to outputs
#
# IMPORTANT: MaxArraySize=1001 on this cluster. Use batch_submit_sobol_sweep2.sh.
#   bash D4_distributed_risk/slurm/batch_submit_sobol_sweep2.sh
#
# Prerequisites (shared with sweep 1 — already complete):
#   ✓ gen_synthetic_flows.py   (50 parquets in results/sobol/synthetic_flows/)
#   ✓ submit_prewarm.sh        (predicted_inflows cache — 50/50 complete)
#   NEW: results/sobol_sweep2/sobol_samples.csv  (generated by sobol_design.py, k=7)

set -euo pipefail

module load python/3.11.5
source ~/dissertation/venv/bin/activate

DISSERTATION_ROOT=~/dissertation
cd "$DISSERTATION_ROOT"

export PYTHONPATH="$DISSERTATION_ROOT/shared:$PYTHONPATH"

BATCH_OFFSET=${BATCH_OFFSET:-0}
TASK_ID=${SLURM_ARRAY_TASK_ID}
SAMPLE_ID=$(( BATCH_OFFSET + TASK_ID ))

echo "Sweep 2 | Array task $TASK_ID | Batch offset $BATCH_OFFSET | Sample ID $SAMPLE_ID"

python D4_distributed_risk/experiments/run_sobol_sweep.py \
    --sample-id     "$SAMPLE_ID" \
    --samples-csv   D4_distributed_risk/results/sobol_sweep2/sobol_samples.csv \
    --syn-flows-dir D4_distributed_risk/results/sobol/synthetic_flows \
    --outdir        D4_distributed_risk/results/sobol_sweep2/task_outputs \
    --n-workers     "$SLURM_CPUS_PER_TASK" \
    --log-level     INFO

echo "Sweep 2 sample $SAMPLE_ID complete"
